title: Stackbit Azimuth Theme
baseURL: /
params:
  footer:
    content: '&copy; Stackbit. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
    logo_img: /images/rodened_vit_b.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: ''
  header:
    has_nav: true
    logo_img: /images/rodened_b.png
    title: Azimuth
    menu:
      actions:
        - label: Sign Up
          url: /signup
  palette: purple
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
